include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/gen/*
  errors:
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    unrelated_type_equality_checks: ignore
    avoid_print: ignore
    invalid_annotation_target: ignore
    prefer_final_fields: ignore
    unnecessary_null_comparison: ignore
    omit_local_variable_types: ignore
linter:
  rules:
    public_member_api_docs: false
